add db path
Kuba77/Manga_store pull request #1
Opened 2021-11-19 19:58 UTC by Misyats-Denis

добавил силку монги в сервер

2021-11-26 07:07 UTC, mvalerii requested changes

2021-11-26 07:07 UTC, mvalerii commented on client/src/api/Api.js
> +const axios = require("axios");
почему Api c большой буквы ?

2021-11-26 07:07 UTC, mvalerii commented on client/src/api/Api.js
> +axios.defaults.baseURL = "http://localhost:3000/api";
переменная ейрвайрмента

2021-11-26 07:07 UTC, mvalerii commented on client/src/api/userApi.js
> +// import axios, { setAuthToken } from "./Api";
удалить !!!! зачем коменты в кодовой базе ?

2021-11-26 07:07 UTC, mvalerii commented on client/src/api/Api.js
> +export const setAuthToken = (token) => {
Может больше смысла сформировать инстанс аксиоса с хедерами и бейз урлами и експортировать его в остальные сервисы ?

2021-11-26 07:07 UTC, mvalerii commented on client/src/components/Header/Header.js
> +  return (
Обобщите логику в рамках компонента сигн ап, вы все сейчас топчитесь у друг друга на ногах. Вы работаете в том же файле и с теми же структурами что и @Arkadii

2021-11-26 07:07 UTC, mvalerii commented on client/src/pages/login-page/LoginPage.jsx
> +import React from "react";
что с неймингом фала откуда тут кебаб кейс !!!

2021-11-26 07:07 UTC, mvalerii commented on client/src/pages/login-page/LoginPage.jsx
> +      <div className="Form zone">
приведите порядок стилистику написание стилей, либо бем либо другую методологию

2021-11-26 07:07 UTC, mvalerii commented on client/src/pages/login-page/LoginPage.jsx
> +          clientId="649718085227-lo924pc5nifh55shg8u0gf3vm7olsmvn.apps.googleusercontent.com"
уберите все токены с клиента это не секюрно

2021-11-26 07:07 UTC, mvalerii commented on client/src/pages/reg-page/regPage.jsx
> +const RegPage = () => {
SingUpPag
ужасный нейминг файлов

2021-11-26 07:07 UTC, mvalerii commented on client/src/pages/reg-page/regPage.jsx
> +// import { useHistory } from "react-router-dom";
убрать

2021-11-26 07:07 UTC, mvalerii commented on client/src/pages/reg-page/regPage.jsx
> +    validationSchema: Yup.object({
вынесите валидаторы в отдельный файл

2021-11-26 07:07 UTC, mvalerii commented on client/src/pages/login-page/LoginPage.jsx
> +    console.log("GOOGLE", response);
убрать

2021-11-26 07:07 UTC, mvalerii commented on client/src/pages/login-page/LoginPage.jsx
> +    logOrRegisterCustomer(response);
переименовать

2021-11-26 07:07 UTC, mvalerii commented on client/src/pages/reg-page/regPage.jsx
> +        <form onSubmit={formik.handleSubmit}>
Переработать форму, большая нечитаемая простыня. Есть повторяющиеся структуры

2021-11-26 07:07 UTC, mvalerii commented on client/src/store/actions/authAction.js
> +// export async function registerCustomer(newCustomer, dispatch) {
почистить код

2021-11-26 07:07 UTC, mvalerii commented on client/src/store/actions/authAction.js
> +    const { token } = await axios.post("/customers", value);
сделайте отдельный метод, вы. уже начали описывать апи, доделайте сервисы. соберите роуты в одном месте.

2021-11-26 07:07 UTC, mvalerii commented on client/src/store/reducer.js
> +// import types from "./types";
убрать

2021-11-26 07:07 UTC, mvalerii commented on client/src/store/redusers/authReducer.js
> +    case AUTH_USER:
успешно не успешно ? как отрабатывается статус когда пользователь не смог пройти аутентификацию

2021-11-26 07:07 UTC, mvalerii commented on client/src/store/redusers/errorsReducer.js
> +      return action.payload;
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

2021-11-26 07:07 UTC, mvalerii commented on client/src/store/redusers/errorsReducer.js
> +const initialState = {};
не вижу структуры, что будет приходит сюда  не понятно. Опишите базовую структуру

2021-11-26 07:07 UTC, mvalerii commented on client/src/store/redusers/index.js
> +
убрать мусор

2021-11-26 07:07 UTC, mvalerii commented on client/src/store2/customer/reducer.js
> +      state = { f: 1 };
формула один ?  что за базовый стейт ?

2021-11-26 07:07 UTC, mvalerii commented on client/src/store2/index.js
> +// import { configureStore } from "@reduxjs/toolkit";
мусор

2021-11-26 07:07 UTC, mvalerii commented on server/.env
> +
отфариотировать

2021-11-26 07:07 UTC, mvalerii commented on server/config/keys_dev.js
> +    "mongodb+srv://admin:admin@cluster0.zwgzm.mongodb.net/myFirstDatabase?retryWrites=true&w=majority",
брать с енвайрмента

2021-11-26 07:07 UTC, mvalerii commented on server/config/passportGoogle.js
> +const GOOGLE_CALLBACK_URL = "http://localhost:5000/api/v1/auth/google";
в енвайрмент

2021-11-26 07:07 UTC, mvalerii commented on server/controllers/customers.js
> +      // console.log(newCustomer);
убрать мусор

2021-11-26 07:07 UTC, mvalerii commented on server/controllers/customers.js
> +              console.log(customer);
убрать

2021-11-26 07:07 UTC, mvalerii commented on server/controllers/google.js
> +  "649718085227-lo924pc5nifh55shg8u0gf3vm7olsmvn.apps.googleusercontent.com"
енвайрмент

2021-11-26 07:07 UTC, mvalerii commented on server/controllers/google.js
> +        "649718085227-lo924pc5nifh55shg8u0gf3vm7olsmvn.apps.googleusercontent.com",
енвармент

2021-11-27 11:28 UTC, Misyats-Denis commented on client/src/api/Api.js
> +axios.defaults.baseURL = "http://localhost:3000/api";
исправлено

2021-11-27 11:28 UTC, Misyats-Denis commented on client/src/api/userApi.js
> +// import axios, { setAuthToken } from "./Api";
исправлено

2021-11-27 11:28 UTC, Misyats-Denis commented on client/src/api/Api.js
> +export const setAuthToken = (token) => {
исправлено

2021-11-27 11:28 UTC, Misyats-Denis commented on client/src/components/Header/Header.js
> +  return (
исправлено

2021-11-27 11:28 UTC, Misyats-Denis commented on client/src/pages/login-page/LoginPage.jsx
> +import React from "react";
исправлено

2021-11-27 11:29 UTC, Misyats-Denis commented on client/src/pages/login-page/LoginPage.jsx
> +      <div className="Form zone">
исправлено

2021-11-27 11:29 UTC, Misyats-Denis commented on client/src/pages/login-page/LoginPage.jsx
> +          clientId="649718085227-lo924pc5nifh55shg8u0gf3vm7olsmvn.apps.googleusercontent.com"
исправлено

2021-11-27 11:30 UTC, Misyats-Denis commented on client/src/pages/reg-page/regPage.jsx
> +const RegPage = () => {
оставил пока так до решение общепринятого нейминга

2021-11-27 11:30 UTC, Misyats-Denis commented on client/src/pages/reg-page/regPage.jsx
> +// import { useHistory } from "react-router-dom";
исправлено

2021-11-27 11:30 UTC, Misyats-Denis commented on client/src/pages/reg-page/regPage.jsx
> +    validationSchema: Yup.object({
исправлено

2021-11-27 11:30 UTC, Misyats-Denis commented on client/src/pages/login-page/LoginPage.jsx
> +    console.log("GOOGLE", response);
исправлено

2021-11-27 11:30 UTC, Misyats-Denis commented on client/src/pages/login-page/LoginPage.jsx
> +    logOrRegisterCustomer(response);
не изменял

2021-11-27 11:31 UTC, Misyats-Denis commented on client/src/pages/reg-page/regPage.jsx
> +        <form onSubmit={formik.handleSubmit}>
форма сделана для проверки логики пока что не исправлял

2021-11-27 11:31 UTC, Misyats-Denis commented on client/src/store/actions/authAction.js
> +// export async function registerCustomer(newCustomer, dispatch) {
исправлено

2021-11-27 11:31 UTC, Misyats-Denis commented on client/src/store/reducer.js
> +// import types from "./types";
исправлено

2021-11-27 11:31 UTC, Misyats-Denis commented on client/src/store/redusers/authReducer.js
> +    case AUTH_USER:
исправлено

2021-11-27 11:31 UTC, Misyats-Denis commented on client/src/store/redusers/errorsReducer.js
> +      return action.payload;
исправлено

2021-11-27 11:32 UTC, Misyats-Denis commented on client/src/store/redusers/errorsReducer.js
> +const initialState = {};
исправлено

2021-11-27 11:32 UTC, Misyats-Denis commented on client/src/store/redusers/index.js
> +
исправлено

2021-11-27 11:32 UTC, Misyats-Denis commented on client/src/store2/customer/reducer.js
> +      state = { f: 1 };
исправлено

2021-11-27 11:32 UTC, Misyats-Denis commented on client/src/store2/index.js
> +// import { configureStore } from "@reduxjs/toolkit";
исправлено

2021-11-27 11:32 UTC, Misyats-Denis commented on server/config/keys_dev.js
> +    "mongodb+srv://admin:admin@cluster0.zwgzm.mongodb.net/myFirstDatabase?retryWrites=true&w=majority",
исправлено

2021-11-29 06:05 UTC, mvalerii commented on client/src/pages/reg-page/regPage.jsx
> +        <form onSubmit={formik.handleSubmit}>
либо переделайте либо удалите

2021-11-29 06:06 UTC, mvalerii commented on client/src/pages/login-page/LoginPage.jsx
> +  async function singIn(info) {
юзколбек

2021-11-29 06:07 UTC, mvalerii commented on server/controllers/customers.js
> +          // console.log(newCustomer);
убрать

2021-11-29 14:45 UTC, Misyats-Denis commented on server/controllers/customers.js
> +          // console.log(newCustomer);
done

2021-11-29 14:45 UTC, Misyats-Denis commented on client/src/pages/login-page/LoginPage.jsx
> +  async function singIn(info) {
done

2021-11-29 15:05 UTC, Misyats-Denis commented on server/controllers/customers.js
> +      // console.log(newCustomer);
dont

2021-11-29 15:17 UTC, mvalerii requested changes

2021-11-29 15:17 UTC, mvalerii commented on client/src/App.js
> +            <h1>==========================</h1>
Что это??

2021-11-29 15:17 UTC, mvalerii commented on client/src/pages/login-page/LoginPage.jsx
> +  const customer = useSelector((state) => state.customer.customerData);
Использовать реселект

2021-11-29 15:17 UTC, mvalerii commented on client/src/pages/login-page/LoginPage.jsx
> +  ////////////////////////////////////////////////////////////////
Что это?

2021-11-29 15:17 UTC, mvalerii commented on client/src/pages/login-page/LoginPage.jsx
> +    [customer]
Бред

2021-11-29 15:17 UTC, mvalerii commented on client/src/pages/reg-page/regPage.jsx
> +    onSubmit: (values) => {
Просто signup

2021-11-29 15:17 UTC, mvalerii commented on server/models/Product.js
> +    ///
Что это?

2021-11-30 19:01 UTC, AlinaBaranetskaya approved these changes

2021-12-01 10:19 UTC, mvalerii approved these changes

2021-12-08 02:57 UTC, closed without merging