Genya
Kuba77/Manga_store pull request #4
Opened 2021-11-25 18:19 UTC by Yevgeniy-Bakalchuk

2021-11-25 19:09 UTC, mvalerii commented on client/src/components/Categories/Categories.js
> +                        <a className={classes.comedy_book} href="#">Comedy
Вынести в общий компонент, копипаст

2021-11-25 22:39 UTC, Yevgeniy-Bakalchuk commented on client/src/components/Categories/Categories.js
> +                        <a className={classes.comedy_book} href="#">Comedy
done

2021-11-26 06:28 UTC, mvalerii reviewed
Дискашены при исправлении можно закрыть самостоятельно

2021-11-26 06:28 UTC, mvalerii commented on .idea/.gitignore
> +# Default ignored files
Убрать из гит

2021-11-26 06:28 UTC, mvalerii commented on .idea/Final_project.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Убрать из гит

2021-11-26 06:28 UTC, mvalerii commented on .idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Убрать из гит

2021-11-26 06:28 UTC, mvalerii commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Убрать из гит

2021-11-26 06:28 UTC, mvalerii commented on client/src/App.js
>  import Header from "./components/Header/Header";
Добавьте реекспорт

2021-11-26 06:28 UTC, mvalerii commented on client/src/App.js
> +import Footer from "./components/Footer/Footer"
Будет конфликт с задачей в которой добавлены роуты

2021-11-26 06:28 UTC, mvalerii commented on client/src/components/Categories/Calc.js
> +const Calc = (props) => {
Бесполезный компонент, слишком блоьшая декомпозиция

2021-11-26 06:28 UTC, mvalerii commented on client/src/components/Categories/Categories.js
> +        <>
Тут не нужен фрагмент

2021-11-26 06:28 UTC, mvalerii commented on client/src/components/Categories/Categories.js
> +                        <CategoriesList />
где пропсы ?

2021-11-26 06:28 UTC, mvalerii commented on client/src/components/Categories/CategoriesItem.js
> +                <Calc
Что делает этот компонент ? 
текстовые пропсы задаются  так ="some string"

2021-11-26 06:28 UTC, mvalerii commented on client/src/components/Categories/CategoriesList.js
> +        <>
копипаста, https://ru.reactjs.org/docs/lists-and-keys.html

2021-11-26 06:28 UTC, mvalerii commented on client/src/components/Footer/FooteLink.js
> +import classes from "./Footer.module.scss"
назврние файлов стилей с маленькой буквы. С большой файлы с js классами или компонентами

2021-11-26 06:28 UTC, mvalerii commented on client/src/components/Footer/FooteLink.js
> +const FooterLink = (props) => {
Зачем нам этот компонент, почему мы не можем просто использовать линк ?

2021-11-26 06:28 UTC, mvalerii commented on client/src/components/Footer/Footer.js
> +                <div className={classes.footer_quick_links}>
Можно обобщит одинаковые с труктуры в  рамках одного компонента

2021-11-26 06:28 UTC, mvalerii commented on client/src/components/Footer/Footer.js
> +                    <FooterIcons />
Корректней это назвать социальными иконками

2021-11-26 06:28 UTC, mvalerii commented on client/src/components/Footer/FooterCustomerAreaLinks.js
> +const FooterCustomerAreaList = () => {
пропс со списком ссылок

2021-11-26 06:28 UTC, mvalerii commented on client/src/components/Footer/FooterCustomerAreaLinks.js
> +const FooterCustomerAreaList = () => {
Название компонента не передает суть, это навигация в футере

2021-11-26 06:28 UTC, mvalerii commented on client/src/components/Footer/FooterIcons.js
> +                        <a className={classes.link_facebook} href="https://www.facebook.com/">
копипаста, это список

2021-11-26 06:28 UTC, mvalerii commented on client/src/components/Footer/FooterQuickLinks.js
> +const FooterQuickList = () =>{
Чем принципиально отличается этот компонент от FooterCustomerAreaList ?

2021-11-26 06:28 UTC, mvalerii commented on client/src/components/Footer/FormSubscribe.js
> +                    console.log(values);
консол лог

2021-11-26 06:28 UTC, mvalerii commented on client/src/components/Footer/FormSubscribe.js
> +function FormSubscribe() {
Я бы реализовал эту часть в рамках задачи про формы

2021-12-01 16:38 UTC, Misyats-Denis requested changes
rename branch name by task id

2021-12-13 11:48 UTC, closed without merging