[FP-8] added functionality of the registered user/ changed cartStore
Kuba77/Manga_store pull request #42
Opened 2021-12-15 15:54 UTC by Misyats-Denis

2021-12-15 15:58 UTC, Arkadii approved these changes

2021-12-15 19:26 UTC, Kuba77 approved these changes

2021-12-16 06:08 UTC, mvalerii requested changes

2021-12-16 06:08 UTC, mvalerii commented on client/package.json
> +    "gh-pages": "^3.2.3",
1. это дев деп 
2. а нужен ли он ?

2021-12-16 06:08 UTC, mvalerii commented on client/src/components/Cart/CartProduct.js
> +const CartProduct = (props) => {
const CartProduct = ({ item, deleteProductFromCart, decreaseProduct, increaseProduct }) => {

2021-12-16 06:08 UTC, mvalerii commented on client/src/components/Cart/CartProduct.js
> +          <div className={classes.cart_button__counter_prod}>
каунтер это компонент

2021-12-16 06:08 UTC, mvalerii commented on client/src/components/Cart/CartProduct.js
> +        <p>$</p>
а если валюта поменяется ? или будет мультивалюта ?

2021-12-16 06:08 UTC, mvalerii commented on client/src/components/Cart/CartProduct.js
> +        <p>50</p>
хардкод !!!

2021-12-16 06:08 UTC, mvalerii commented on client/src/components/Cart/CartProductList.js
> +import { InCart } from "../../store/selectors";
нейминг

2021-12-16 06:08 UTC, mvalerii commented on client/src/components/Cart/CartProductList.js
> +import { customerData } from "../../store/selectors";
за один импорт можно вытянуть все

2021-12-16 06:08 UTC, mvalerii commented on client/src/components/Cart/CartProductList.js
> +    console.log("cart chenge");
сонсол лог

2021-12-16 06:08 UTC, mvalerii commented on client/src/components/Cart/CartProductList.js
> +    [setCart]
бред 2

2021-12-16 06:08 UTC, mvalerii commented on client/src/components/Cart/CartProductList.js
> +    console.log("cart", _id);
убрать

2021-12-16 06:08 UTC, mvalerii commented on client/src/components/Cart/CartProductList.js
> +    [deleteItemFromCart, InCart(store)]
InCart(store) сохраните в перемнную

2021-12-16 06:08 UTC, mvalerii commented on client/src/components/Cart/CartProductList.js
> +    [setCart]
опять

2021-12-16 06:08 UTC, mvalerii commented on client/src/components/Cart/CartProductList.js
> +    getCart();
колбек ради юз ефекта которы отработает раз

2021-12-16 06:08 UTC, mvalerii commented on client/src/components/Cart/CartProductList.js
> +    <>
зачем фрагмент к месту и нет ? Это не читаемо

2021-12-16 06:08 UTC, mvalerii commented on client/src/components/Cart/CartProductList.js
> +            <div className={classes.favorites__noitem}>
это компонент с заглушкой

2021-12-16 06:08 UTC, mvalerii commented on client/src/components/Cart/CartProductList.js
> +          ) : (
уберите эти тернары

2021-12-16 06:08 UTC, mvalerii commented on client/src/components/Cart/CartProductList.js
> +          ) : (
https://github.com/acdlite/recompose/blob/master/docs/API.md#branch может помочь

2021-12-16 06:08 UTC, mvalerii commented on client/src/components/Feature/Carousel/Carousel.jsx
> +        slidesPerView={size < 768 ? 3 : "auto"}
вынесите в отдельную тулзу

2021-12-16 06:08 UTC, mvalerii commented on client/src/components/Filters/Filters.jsx
> +const Filters = (props) => {
писал выше

2021-12-16 06:08 UTC, mvalerii commented on client/src/components/Filters/Filters.jsx
>            getselectedGenre={getselectedGenre}
нейминг

2021-12-16 06:08 UTC, mvalerii commented on client/src/components/Filters/Filters.jsx
>            getselectedGenre={getselectedGenre}
чекбокс возвращает тру либо фолз. скорее это контролы корректнее назвать

2021-12-16 06:08 UTC, mvalerii commented on client/src/components/Filters/checkboxFilter/СheckboxFilter.jsx
> +    <div className={classes.checkbox__container}>
рендер списка это а не копипаста должна быть

2021-12-16 06:08 UTC, mvalerii commented on client/src/components/Forms/LoginForm.jsx
> +            console.log("customerCart", customerCart);
убрать

2021-12-16 06:08 UTC, mvalerii commented on client/src/components/Forms/LoginForm.jsx
> +            console.log("customerCart", customerCart);
тяжело читать, нужен рефакторинг

2021-12-16 06:08 UTC, mvalerii commented on client/src/components/Product/Product.js
> +      console.log(q);
убрать

2021-12-16 06:08 UTC, mvalerii commented on client/src/components/Product/Product.js
> +      let q = {};
ку ?

2021-12-16 06:08 UTC, mvalerii commented on client/src/components/Product/Product.js
> +        console.log("Anonim");
добавьте в линтер правило для консол лога что бы по рукам било

2021-12-16 06:08 UTC, mvalerii commented on client/src/components/Product/Product.js
> +      let q = {};
переписть эту часть

2021-12-16 06:08 UTC, mvalerii commented on client/src/pages/CollectionPage/CollectionPage.js
> +        {isLoading && (
тернар не ?

2021-12-16 06:08 UTC, mvalerii commented on client/src/pages/FavoritesPage/FavoritesPage.js
> +        <Header />
что то пошло не так

2021-12-16 06:08 UTC, mvalerii commented on client/src/pages/FavoritesPage/FavoritesPage.js
> +                <div className={classes.favorites__noitem}>
где то я это уже видел

2021-12-16 06:08 UTC, mvalerii commented on client/src/pages/FavoritesPage/FavoritesPage.js
> +                imgSrc={item.imageUrls[2]}
а если 3 ?

2021-12-16 06:08 UTC, mvalerii commented on client/src/pages/LoginPage/LoginPage.jsx
> +            console.log("customerCart", customerCart);
-

2021-12-16 06:08 UTC, mvalerii commented on client/src/pages/LoginPage/LoginPage.jsx
> +            customerCart.products.forEach(function (item) {
выглядит как плохое решение, почему бы сразу не формировать стейт на основании нашего локал стореджа

2021-12-16 06:08 UTC, mvalerii commented on client/src/services/cart.js
> +      .then((res) => {
слонылюдиптицы, зачем евейт и зен чейн ?

2021-12-16 06:08 UTC, mvalerii commented on client/src/services/cart.js
> +        console.log(res);
убрать

2021-12-16 06:08 UTC, mvalerii commented on client/src/services/htttWraper.js
> +  console.log("if (JWTToken)", JWTToken);
-----

2021-12-16 06:08 UTC, mvalerii commented on client/src/store/cart/reducer.js
> +      state.products.push(action.payload);
ой плохо, хочу иммутабельности

2021-12-16 06:08 UTC, mvalerii commented on client/src/utils/utils.js
> +export const addItemQuantity = (arr, _id) => {
перепишите

2021-12-16 17:15 UTC, merged