StoreFeatures section
Kuba77/Manga_store pull request #6
Opened 2021-11-25 18:25 UTC by brizhem

2021-11-25 18:37 UTC, brizhem commented
Секция с кратким описанием доставки, оплаты, возврат товара

2021-11-25 19:00 UTC, mvalerii commented on client/src/components/StoreFeatures/StoreFeatures.jsx
> +            <div className="store-features__item">
Копипаст, есть смысл вынести в общий компонент

2021-11-25 19:03 UTC, mvalerii approved these changes, later dismissed
Test approve

2021-11-26 06:38 UTC, mvalerii requested changes

2021-11-26 06:38 UTC, mvalerii commented on client/src/App.js
> +import StoreFeatures from "./components/StoreFeatures/StoreFeatures";
Не информативное название компонента ?

2021-11-26 06:38 UTC, mvalerii commented on client/src/components/StoreFeatures/StoreFeatures.jsx
> +import "./StoreFeatures.scss";
можно назвать просто styles  по названию папки и так будет понятно для чего эти стили

2021-11-26 20:58 UTC, closed without merging