FP[Order-page]: Order page+letter html
Kuba77/Manga_store pull request #68
Opened 2022-01-10 19:20 UTC by feschenkodima

2022-01-10 19:26 UTC, AlinaBaranetskaya approved these changes

2022-01-10 20:11 UTC, Kuba77 approved these changes

2022-01-11 06:28 UTC, mvalerii requested changes

2022-01-11 06:28 UTC, mvalerii commented on client/src/components/Basket/BasketHeader.js
> +            <div className={classes.basket__header_wrap}>
Поменяйте хардкод на рендер списка

2022-01-11 06:28 UTC, mvalerii commented on client/src/components/Basket/BasketItem.js
> +                        <AiOutlineMinus color='#8D28AD' size={20} onClick={(e) => {
такие обработчики не допустимы, вас за них будут сильно ругать !

2022-01-11 06:28 UTC, mvalerii commented on client/src/components/Forms/ValidationSchema.js
> +const emailRegex =
насколько знаю проверку можно сделать через юп а не через регулярку yup.string().email()

2022-01-11 06:28 UTC, mvalerii commented on client/src/components/Order-page/Order-list/Order-list.js
> +    <>
зачем тут фрагмент ?

2022-01-11 06:28 UTC, mvalerii commented on client/src/components/Order-page/Order-page.js
> +      country: customerData.deliveryAdress?.country
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator

2022-01-11 06:28 UTC, mvalerii commented on client/src/pages/CartPage/CartPage.js
> +      {/* <CartHeader />
уберите весь закоментированный код по пр

2022-01-11 08:18 UTC, feschenkodima commented on client/src/components/Forms/ValidationSchema.js
> +const emailRegex =
Можно, но в таком случае, пропускает кириллицу

2022-01-11 09:25 UTC, merged